Improved handling of array from bash script

diff --git a/.github/workflows/stage-3-build.yaml b/.github/workflows/stage-3-build.yaml
--- a/.github/workflows/stage-3-build.yaml
+++ b/.github/workflows/stage-3-build.yaml
@@ -162,7 +162,7 @@ jobs:
           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
 
       - name: ghcr.io login
-        if: github.ref == 'refs/heads/main' && env.USE_AZURECR == 'false' || env.IS_TEST_DEPLOY == 'true'
+        if: (github.ref == 'refs/heads/main' && env.USE_AZURECR == 'false') || env.IS_TEST_DEPLOY == 'true'
         uses: docker/login-action@v3
         with:
           registry: ghcr.io
@@ -262,12 +262,15 @@ jobs:
           GH_TOKEN: ${{ github.token }}
           REGISTRY: ghcr.io/${{ github.repository_owner }}
           docker_services: ${{ needs.containers-to-build.outputs.docker_services }}
+          PROJECT_NAME: ${{ inputs.project_name }}
         run: |
           echo Running 'docker buildx imagetools' on remote repositories...
 
-          for service in $docker_services; do
-            echo "Adding tag ${package}:${SHORT_COMMIT_HASH} to ${service}..."
-            docker buildx imagetools create "${REGISTRY,,}/${service,,}:${PR_NUM_TAG}" --tag "${REGISTRY,,}/${service,,}:${SHORT_COMMIT_HASH}" || echo "Tagging failed for $service"
+          services=($(echo "$docker_services" | jq -r '.[]'))
+          for service in "${services[@]}"; do
+            image_name="${PROJECT_NAME}-${service}"
+            echo "Adding tag ${SHORT_COMMIT_HASH} to ${image_name}..."
+            docker buildx imagetools create "${REGISTRY,,}/${image_name,,}:${PR_NUM_TAG}" --tag "${REGISTRY,,}/${image_name,,}:${SHORT_COMMIT_HASH}" || echo "Tagging failed for $service"
           done
 
   aggregate-reports:
