GitHub repos must be in lowercase Add some log output if docker buildx fails

diff --git a/.github/workflows/stage-3-build.yaml b/.github/workflows/stage-3-build.yaml
--- a/.github/workflows/stage-3-build.yaml
+++ b/.github/workflows/stage-3-build.yaml
@@ -119,15 +119,19 @@ jobs:
         working-directory: ${{ steps.get-function-names.outputs.DOCKER_COMPOSE_DIR }}
         continue-on-error: false
         env:
-          IMAGE_NAME: ${{ inputs.project_name }}-${{ matrix.function }}
           PR_NUM_TAG: ${{ steps.tags.outputs.pr_num_tag }}
           COMMIT_HASH_TAG: ${{ steps.tags.outputs.short_commit_hash }}
+          IMAGE_NAME: ${{ inputs.project_name }}-${{ matrix.function }}
           REPO_PATH: ${{ steps.tags.outputs.registry_repository_path }}
         run: |
           docker compose -f ${COMPOSE_FILE//,/ -f } -p ${PROJECT_NAME} build --no-cache --pull ${{ matrix.function }}
-          docker tag ${IMAGE_NAME}:latest "${REPO_PATH}:${COMMIT_HASH_TAG}"
-          docker tag ${IMAGE_NAME}:latest "${REPO_PATH}:${PR_NUM_TAG}"
-          docker tag ${IMAGE_NAME}:latest "${REPO_PATH}:${ENVIRONMENT_TAG}"
+
+          IMAGE_NAME_LOWER=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')
+          REPO_PATH_LOWER=$(echo "$REPO_PATH" | tr '[:upper:]' '[:lower:]')
+
+          docker tag ${IMAGE_NAME_LOWER}:latest "${REPO_PATH_LOWER}:${COMMIT_HASH_TAG}"
+          docker tag ${IMAGE_NAME_LOWER}:latest "${REPO_PATH_LOWER}:${PR_NUM_TAG}"
+          docker tag ${IMAGE_NAME_LOWER}:latest "${REPO_PATH_LOWER}:${ENVIRONMENT_TAG}"
 
       - name: Az CLI login
         if: github.ref == 'refs/heads/main' && env.USE_AZURECR == 'true'
@@ -154,15 +158,17 @@ jobs:
         working-directory: ${{ steps.get-function-names.outputs.DOCKER_COMPOSE_DIR }}
         continue-on-error: false
         env:
-          IMAGE_NAME: ${{ inputs.project_name }}-${{ matrix.function }}
           PR_NUM_TAG: ${{ steps.tags.outputs.pr_num_tag }}
           COMMIT_HASH_TAG: ${{ steps.tags.outputs.short_commit_hash }}
           REPO_PATH: ${{ steps.tags.outputs.registry_repository_path }}
+          IMAGE_NAME: ${{ inputs.project_name }}-${{ matrix.function }}
           GH_TOKEN: ${{ github.token }}
         run: |
-          docker push "${REPO_PATH}:${COMMIT_HASH_TAG}"
-          docker push "${REPO_PATH}:${PR_NUM_TAG}"
-          docker push "${REPO_PATH}:${ENVIRONMENT_TAG}"
+          REPO_PATH_LOWER=$(echo "$REPO_PATH" | tr '[:upper:]' '[:lower:]')
+
+          docker push "${REPO_PATH_LOWER}:${COMMIT_HASH_TAG}"
+          docker push "${REPO_PATH_LOWER}:${PR_NUM_TAG}"
+          docker push "${REPO_PATH_LOWER}:${ENVIRONMENT_TAG}"
 
       - name: Software Bill of Materials (SBOM)
         id: sbom
@@ -236,9 +242,11 @@ jobs:
           GH_TOKEN: ${{ github.token }}
           REGISTRY: ghcr.io/${{ github.repository_owner }}
         run: |
+          REGISTRY_LOWER=$(echo "$REGISTRY" | tr '[:upper:]' '[:lower:]')
+
           packages=$(gh api /repos/{owner}/{repo}/packages?package_type=container --jq '.[].name')
           for package in ${packages}; do
-            docker buildx imagetools create "${REGISTRY}/${package}:${ENVIRONMENT_TAG}" --tag "${REGISTRY}/${package}:${SHORT_COMMIT_HASH}"
+            docker buildx imagetools create "${REGISTRY_LOWER}/${package}:${ENVIRONMENT_TAG}" --tag "${REGISTRY_LOWER}/${package}:${SHORT_COMMIT_HASH}" || echo "Tagging failed for $package"
           done
 
   aggregate-reports:
