Improve naming convention for clearer understanding Remove redundant step for buildx Ensure az acr login uses correct reference

diff --git a/.github/workflows/stage-3-build.yaml b/.github/workflows/stage-3-build.yaml
--- a/.github/workflows/stage-3-build.yaml
+++ b/.github/workflows/stage-3-build.yaml
@@ -93,6 +93,7 @@ jobs:
       docker_compose_dir: ${{ steps.get-function-names.outputs.DOCKER_COMPOSE_DIR }}
       pr_num_tag: ${{ steps.tags.outputs.pr_num_tag }}
       short_commit_hash: ${{ steps.tags.outputs.short_commit_hash }}
+      container_registry: ${{ env.USE_AZURECR == 'true' && format('{0}.azurecr.io', env.ACR_NAME) || format('ghcr.io/{0}', github.repository_owner) }}
     steps:
       - uses: actions/checkout@v4
         with:
@@ -122,17 +123,20 @@ jobs:
         run: |
           PR_NUMBER="${{ github.event.pull_request.number }}"
 
-          if [ -z "$PR_NUMBER" ]; then
-            echo "Looking up PR number for commit: $GITHUB_SHA"
+          if [[ -z "$PR_NUMBER" ]]; then
+            echo "Looking up (open) PR number for commit: $GITHUB_SHA"
             PR_NUMBER=$(gh pr list --state open --search "$GITHUB_SHA" --json number -q '.[0].number' 2>/dev/null || true)
           fi
 
-          if [ -z "$PR_NUMBER" ]; then
+          if [[ -z "$PR_NUMBER" ]]; then
+            echo "Looking up (merged) PR number for commit: $GITHUB_SHA"
             PR_NUMBER=$(gh pr list --state merged --search "$GITHUB_SHA" --json number -q '.[0].number' 2>/dev/null || true)
           fi
 
-          set -x
-          [[ "${GITHUB_REF}" == "refs/heads/main" ]] && PR_NUMBER=$(gh api repos/{owner}/{repo}/commits/${GITHUB_SHA}/pulls --jq 'sort_by(.updated_at) | reverse | .[0].number')
+          if [[ -z "$PR_NUMBER" ]] && [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
+            echo "Looking up (main) PR number for commit: $GITHUB_SHA"
+            PR_NUMBER=$(gh api repos/{owner}/{repo}/commits/${GITHUB_SHA}/pulls --jq 'sort_by(.updated_at) | reverse | .[0].number')
+          fi
 
           echo "Resolved PR number: ${PR_NUMBER}"
           echo "pr_num_tag=pr${PR_NUMBER}" >> "${GITHUB_OUTPUT}"
@@ -172,24 +176,24 @@ jobs:
         working-directory: ${{ needs.containers-to-build.outputs.docker_compose_dir }}
         continue-on-error: false
         env:
-          IMAGE_NAME: ${{ inputs.project_name }}-${{ matrix.function }}
-          PR_NUM_TAG: ${{ needs.containers-to-build.outputs.pr_num_tag }}
-          SHORT_COMMIT_HASH: ${{ needs.containers-to-build.outputs.short_commit_hash }}
-          REGISTRY: ${{ env.USE_AZURECR == 'true' && format('{0}.azurecr.io', env.ACR_NAME) || format('ghcr.io/{0}', github.repository_owner) }}
+          image_name: ${{ inputs.project_name }}-${{ matrix.function }}
+          pr_num_tag: ${{ needs.containers-to-build.outputs.pr_num_tag }}
+          short_commit_hash: ${{ needs.containers-to-build.outputs.short_commit_hash }}
+          container_registry: ${{ needs.containers-to-build.outputs.container_registry }}
           TEST_DEPLOY: ${{ env.IS_TEST_DEPLOY }}
         run: |
           echo "is_test_deploy=${TEST_DEPLOY}" >> "${GITHUB_OUTPUT}"
 
-          repository_path="${REGISTRY,,}/${IMAGE_NAME,,}"
-          echo "repository_path=${repository_path}" >> "${GITHUB_OUTPUT}"
-          echo repository_path=${repository_path}
+          registry_image="${container_registry,,}/${image_name,,}"
+          echo "registry_image=${registry_image}" >> "${GITHUB_OUTPUT}"
+          echo registry_image=${registry_image}
 
           echo Docker compose...
           docker compose -f ${COMPOSE_FILE//,/ -f } -p ${PROJECT_NAME} build --no-cache --pull ${{ matrix.function }}
 
           echo "Docker tag with (${PR_NUM_TAG})..."
-          docker tag ${IMAGE_NAME}:latest "${repository_path}:${PR_NUM_TAG}"
-          [[ -n "${ENVIRONMENT_TAG}" ]] && docker tag "${IMAGE_NAME}:latest" "${repository_path}:${ENVIRONMENT_TAG}"
+          docker tag ${image_name}:latest "${registry_image}:${pr_num_tag}"
+          [[ -n "${ENVIRONMENT_TAG}" ]] && docker tag "${image_name}:latest" "${registry_image}:${ENVIRONMENT_TAG}"
 
       - name: AzureCLI login
         if: (github.ref == 'refs/heads/main' && env.USE_AZURECR == 'true') || env.IS_TEST_DEPLOY == 'true'
@@ -212,13 +216,13 @@ jobs:
         working-directory: ${{ needs.containers-to-build.outputs.docker_compose_dir }}
         continue-on-error: false
         env:
-          PR_NUM_TAG: ${{ needs.containers-to-build.outputs.pr_num_tag }}
-          SHORT_COMMIT_HASH: ${{ needs.containers-to-build.outputs.short_commit_hash }}
-          repository_path: ${{ steps.docker_image.outputs.repository_path }}
+          pr_num_tag: ${{ needs.containers-to-build.outputs.pr_num_tag }}
+          short_commit_hash: ${{ needs.containers-to-build.outputs.short_commit_hash }}
+          registry_image: ${{ steps.docker_image.outputs.registry_image }}
         run: |
           [[ "${USE_AZURECR}" == "true" ]] && az acr login --name "${ACR_NAME}"
-          [[ -n "${ENVIRONMENT_TAG}" ]] && docker push "${repository_path}:${ENVIRONMENT_TAG}"
-          docker push "${repository_path}:${PR_NUM_TAG}"
+          [[ -n "${ENVIRONMENT_TAG}" ]] && docker push "${registry_image}:${ENVIRONMENT_TAG}"
+          docker push "${registry_image}:${pr_num_tag}"
 
       - name: Software Bill of Materials (SBOM)
         id: sbom
@@ -238,8 +242,9 @@ jobs:
     runs-on: ubuntu-latest
     needs: [build-and-push, containers-to-build]
     env:
-      PR_NUM_TAG: ${{ needs.containers-to-build.outputs.pr_num_tag }}
-      SHORT_COMMIT_HASH: ${{ needs.containers-to-build.outputs.short_commit_hash }}
+      pr_num_tag: ${{ needs.containers-to-build.outputs.pr_num_tag }}
+      short_commit_hash: ${{ needs.containers-to-build.outputs.short_commit_hash }}
+      container_registry: ${{ needs.containers-to-build.outputs.container_registry }}
     permissions:
       id-token: write
       contents: read
@@ -258,7 +263,7 @@ jobs:
           ref: dev-dtoss-8958
 
       - name: AzureCLI login
-        if: env.USE_AZURECR == 'true'
+        if: (env.USE_AZURECR == 'true') || env.IS_TEST_DEPLOY == 'true'
         uses: azure/login@v2
         with:
           client-id: ${{ secrets.AZURE_CLIENT_ID }}
@@ -273,12 +278,12 @@ jobs:
           username: ${{ github.actor }}
           password: ${{ github.token }}
 
-      - name: Tag all Azure Container images
+      - name: Tag all Registry Container images
         if: env.USE_AZURECR == 'true'
         env:
           REGISTRY: ${{ env.ACR_NAME }}
           docker_services: ${{ needs.containers-to-build.outputs.docker_services }}
-          PROJECT_NAME: ${{ inputs.project_name }}
+          project_name: ${{ inputs.project_name }}
         run: |
           # wait_for_completion() {
           #   # acr tasks are backgrounded for parallelism
@@ -299,32 +304,17 @@ jobs:
 
           echo Running 'docker buildx imagetools' on remote repositories...
 
-          if [[ ${USE_AZURECR} == 'true' ]; then
+          if [[ ${USE_AZURECR} == 'true' ]]; then
             az acr login --name "${ACR_NAME}"
           fi
 
           services=($(echo "$docker_services" | jq -r '.[]'))
           for service in "${services[@]}"; do
-            image_name="${PROJECT_NAME}-${service}"
-            echo "Adding tag ${SHORT_COMMIT_HASH} to ${image_name}..."
-            docker buildx imagetools create "${REGISTRY,,}/${image_name,,}:${PR_NUM_TAG}" --tag "${REGISTRY,,}/${image_name,,}:${SHORT_COMMIT_HASH}" || echo "Tagging failed for $service"
-          done
-
-      - name: Tag all GitHub packages
-        if: env.USE_AZURECR == 'false' || env.IS_TEST_DEPLOY == 'true'
-        env:
-          GH_TOKEN: ${{ github.token }}
-          registry: ghcr.io/${{ github.repository_owner }}
-          docker_services: ${{ needs.containers-to-build.outputs.docker_services }}
-          project_name: ${{ inputs.project_name }}
-        run: |
-          echo Running 'docker buildx imagetools' on remote repositories...
-
-          services=($(echo "$docker_services" | jq -r '.[]'))
-          for service in "${services[@]}"; do
             image_name="${project_name}-${service}"
-            echo "Adding tag ${SHORT_COMMIT_HASH} to ${image_name}..."
-            docker buildx imagetools create "${registry,,}/${image_name,,}:${PR_NUM_TAG}" --tag "${registry,,}/${image_name,,}:${SHORT_COMMIT_HASH}" || echo "Tagging failed for $service"
+            registry_image=${container_registry,,}/${image_name,,}
+
+            echo "Adding tag ${short_commit_hash} to ${image_name}..."
+            docker buildx imagetools create "${registry_image}:${pr_num_tag}" --tag "${registry_image}:${short_commit_hash}" || echo "Tagging failed for $service"
           done
 
   aggregate-reports:
